[2024-08-01T17:09:36.196+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T17:09:36.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.create_dim_user_type manual__2024-08-01T17:09:27.168537+00:00 [queued]>
[2024-08-01T17:09:36.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.create_dim_user_type manual__2024-08-01T17:09:27.168537+00:00 [queued]>
[2024-08-01T17:09:36.240+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-01T17:09:36.263+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_dim_user_type> on 2024-08-01 17:09:27.168537+00:00
[2024-08-01T17:09:36.296+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=776) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-01T17:09:36.302+0000] {standard_task_runner.py:64} INFO - Started process 784 to run task
[2024-08-01T17:09:36.305+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'create_dim_user_type', 'manual__2024-08-01T17:09:27.168537+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpkl5p7zna']
[2024-08-01T17:09:36.308+0000] {standard_task_runner.py:91} INFO - Job 135: Subtask create_dim_user_type
[2024-08-01T17:09:36.469+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.create_dim_user_type manual__2024-08-01T17:09:27.168537+00:00 [running]> on host e27a9ccca098
[2024-08-01T17:09:36.782+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='create_dim_user_type' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T17:09:27.168537+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T17:09:27.168537+00:00'
[2024-08-01T17:09:36.785+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T17:09:36.787+0000] {sql.py:282} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS DimUserType (
                id_user_type INT PRIMARY KEY,
                user_type VARCHAR(255)
            );
        
[2024-08-01T17:09:36.838+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-01T17:09:36.942+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-01T17:09:37.054+0000] {sql.py:495} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS DimUserType (
                id_user_type INT PRIMARY KEY,
                user_type VARCHAR(255)
            );
        , parameters: None
[2024-08-01T17:09:37.076+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T17:09:37.104+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=create_dim_user_type, run_id=manual__2024-08-01T17:09:27.168537+00:00, execution_date=20240801T170927, start_date=20240801T170936, end_date=20240801T170937
[2024-08-01T17:09:37.185+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-01T17:09:37.277+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T17:09:37.284+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
