[2024-08-05T01:00:13.377+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T01:00:13.409+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_campaign scheduled__2024-08-05T00:50:00+00:00 [queued]>
[2024-08-05T01:00:13.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_campaign scheduled__2024-08-05T00:50:00+00:00 [queued]>
[2024-08-05T01:00:13.424+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T01:00:13.443+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_dimensao_campaign> on 2024-08-05 00:50:00+00:00
[2024-08-05T01:00:13.462+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T01:00:13.470+0000] {standard_task_runner.py:64} INFO - Started process 357 to run task
[2024-08-05T01:00:13.468+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_dimensao_campaign', 'scheduled__2024-08-05T00:50:00+00:00', '--job-id', '1660', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp1eizewxf']
[2024-08-05T01:00:13.484+0000] {standard_task_runner.py:91} INFO - Job 1660: Subtask carga_dimensao_campaign
[2024-08-05T01:00:13.736+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_dimensao_campaign scheduled__2024-08-05T00:50:00+00:00 [running]> on host 59ce2ba01338
[2024-08-05T01:00:14.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_dimensao_campaign' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T00:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-05T00:50:00+00:00'
[2024-08-05T01:00:14.260+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T01:00:14.519+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T01:00:14.563+0000] {logging_mixin.py:188} INFO - Dados inseridos na tabela DimCampaign com sucesso.
[2024-08-05T01:00:14.567+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T01:00:14.572+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T01:00:14.611+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_dimensao_campaign, run_id=scheduled__2024-08-05T00:50:00+00:00, execution_date=20240805T005000, start_date=20240805T010013, end_date=20240805T010014
[2024-08-05T01:00:14.675+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T01:00:14.743+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T01:00:14.747+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
