[2024-08-04T23:58:42.404+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T23:58:42.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_campaign manual__2024-08-04T23:58:28.189168+00:00 [queued]>
[2024-08-04T23:58:42.422+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.carga_dimensao_campaign manual__2024-08-04T23:58:28.189168+00:00 [queued]>
[2024-08-04T23:58:42.423+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T23:58:42.431+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): carga_dimensao_campaign> on 2024-08-04 23:58:28.189168+00:00
[2024-08-04T23:58:42.441+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3504) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T23:58:42.443+0000] {standard_task_runner.py:64} INFO - Started process 3510 to run task
[2024-08-04T23:58:42.443+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'carga_dimensao_campaign', 'manual__2024-08-04T23:58:28.189168+00:00', '--job-id', '1449', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp22nao0m3']
[2024-08-04T23:58:42.444+0000] {standard_task_runner.py:91} INFO - Job 1449: Subtask carga_dimensao_campaign
[2024-08-04T23:58:42.499+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.carga_dimensao_campaign manual__2024-08-04T23:58:28.189168+00:00 [running]> on host 88edf8e2824b
[2024-08-04T23:58:42.595+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='carga_dimensao_campaign' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T23:58:28.189168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T23:58:28.189168+00:00'
[2024-08-04T23:58:42.597+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T23:58:42.680+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T23:58:42.712+0000] {logging_mixin.py:188} INFO - Dados inseridos na tabela DimCampaign com sucesso.
[2024-08-04T23:58:42.713+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T23:58:42.714+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T23:58:42.732+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=carga_dimensao_campaign, run_id=manual__2024-08-04T23:58:28.189168+00:00, execution_date=20240804T235828, start_date=20240804T235842, end_date=20240804T235842
[2024-08-04T23:58:42.753+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T23:58:42.799+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-04T23:58:42.803+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
