[2024-08-04T23:10:14.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T23:10:14.369+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data scheduled__2024-08-04T23:00:00+00:00 [queued]>
[2024-08-04T23:10:14.372+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.fetch_dim_data scheduled__2024-08-04T23:00:00+00:00 [queued]>
[2024-08-04T23:10:14.372+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T23:10:14.379+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_dim_data> on 2024-08-04 23:00:00+00:00
[2024-08-04T23:10:14.384+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2036) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T23:10:14.385+0000] {standard_task_runner.py:64} INFO - Started process 2038 to run task
[2024-08-04T23:10:14.385+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'fetch_dim_data', 'scheduled__2024-08-04T23:00:00+00:00', '--job-id', '1312', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp4fismoaq']
[2024-08-04T23:10:14.386+0000] {standard_task_runner.py:91} INFO - Job 1312: Subtask fetch_dim_data
[2024-08-04T23:10:14.417+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.fetch_dim_data scheduled__2024-08-04T23:00:00+00:00 [running]> on host 88edf8e2824b
[2024-08-04T23:10:14.471+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='fetch_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T23:00:00+00:00'
[2024-08-04T23:10:14.472+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T23:10:14.479+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T23:10:14.565+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-04T23:10:14.567+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T23:10:14.575+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=fetch_dim_data, run_id=scheduled__2024-08-04T23:00:00+00:00, execution_date=20240804T230000, start_date=20240804T231014, end_date=20240804T231014
[2024-08-04T23:10:14.615+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T23:10:14.630+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-04T23:10:14.631+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
