[2024-08-04T19:27:06.013+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T19:27:06.165+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.create_dim_user_type manual__2024-08-04T19:26:18.753537+00:00 [queued]>
[2024-08-04T19:27:06.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.create_dim_user_type manual__2024-08-04T19:26:18.753537+00:00 [queued]>
[2024-08-04T19:27:06.193+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T19:27:06.273+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_dim_user_type> on 2024-08-04 19:26:18.753537+00:00
[2024-08-04T19:27:06.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1064) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-04T19:27:06.323+0000] {standard_task_runner.py:64} INFO - Started process 1069 to run task
[2024-08-04T19:27:06.326+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'create_dim_user_type', 'manual__2024-08-04T19:26:18.753537+00:00', '--job-id', '789', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpc0ke9c0d']
[2024-08-04T19:27:06.334+0000] {standard_task_runner.py:91} INFO - Job 789: Subtask create_dim_user_type
[2024-08-04T19:27:06.933+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.create_dim_user_type manual__2024-08-04T19:26:18.753537+00:00 [running]> on host 83ccd21ce624
[2024-08-04T19:27:07.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='create_dim_user_type' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T19:26:18.753537+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T19:26:18.753537+00:00'
[2024-08-04T19:27:07.422+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T19:27:07.424+0000] {sql.py:282} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS DimUserType (
                id_user_type SERIAL PRIMARY KEY,
                user_type VARCHAR(255)
            );
        
[2024-08-04T19:27:07.478+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T19:27:07.532+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-04T19:27:07.632+0000] {sql.py:495} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS DimUserType (
                id_user_type SERIAL PRIMARY KEY,
                user_type VARCHAR(255)
            );
        , parameters: None
[2024-08-04T19:27:07.752+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T19:27:07.812+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=create_dim_user_type, run_id=manual__2024-08-04T19:26:18.753537+00:00, execution_date=20240804T192618, start_date=20240804T192706, end_date=20240804T192707
[2024-08-04T19:27:08.076+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-04T19:27:08.413+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
