[2024-08-05T00:06:58.528+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T00:06:58.548+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.create_dim_company manual__2024-08-05T00:06:45.469399+00:00 [queued]>
[2024-08-05T00:06:58.560+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.create_dim_company manual__2024-08-05T00:06:45.469399+00:00 [queued]>
[2024-08-05T00:06:58.561+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-05T00:06:58.573+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_dim_company> on 2024-08-05 00:06:45.469399+00:00
[2024-08-05T00:06:58.587+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3885) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-05T00:06:58.606+0000] {standard_task_runner.py:64} INFO - Started process 3891 to run task
[2024-08-05T00:06:58.613+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'create_dim_company', 'manual__2024-08-05T00:06:45.469399+00:00', '--job-id', '1491', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpahz1d0mq']
[2024-08-05T00:06:58.621+0000] {standard_task_runner.py:91} INFO - Job 1491: Subtask create_dim_company
[2024-08-05T00:06:58.729+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.create_dim_company manual__2024-08-05T00:06:45.469399+00:00 [running]> on host 88edf8e2824b
[2024-08-05T00:06:58.838+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gabriel Almeida' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='create_dim_company' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T00:06:45.469399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-05T00:06:45.469399+00:00'
[2024-08-05T00:06:58.846+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T00:06:58.847+0000] {sql.py:282} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS DimCompany (
                id_company SERIAL PRIMARY KEY,
                company VARCHAR(255) UNIQUE NOT NULL
            );
        
[2024-08-05T00:06:58.874+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T00:06:58.884+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-08-05T00:06:58.903+0000] {sql.py:495} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS DimCompany (
                id_company SERIAL PRIMARY KEY,
                company VARCHAR(255) UNIQUE NOT NULL
            );
        , parameters: None
[2024-08-05T00:06:58.906+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T00:06:58.917+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=create_dim_company, run_id=manual__2024-08-05T00:06:45.469399+00:00, execution_date=20240805T000645, start_date=20240805T000658, end_date=20240805T000658
[2024-08-05T00:06:58.965+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T00:06:58.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
